version: '2'
# version: '3.7'

services:
  web:
    container_name: vuln-nginx
    # image: zebboudj/laravel-ctf-nginx:latest
    image: nginx:1.10
    ports:
      - 1234:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d:cached
      - .:/var/www/html:cached

  app:
    container_name: vuln-app
    build:
      context: .
    volumes:
      - .:/var/www/html:cached
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    PMA_HOST: vuln-database

  database:
    container_name: vuln-database
    # image: zebboudj/laravel-ctf-bdd:latest
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      - "MYSQL_USER=lebeaujack"
      - "MYSQL_PASSWORD=etalonducul"
      - "MYSQL_DATABASE=vulnerable_app"
      - "MYSQL_ROOT_PASSWORD=etalonducul"
    # volumes:
      # - my-datavolume:/var/lib/mysql
# volumes: 
  # my-datavolume:
